// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: stockDetailService.proto

package services

import (
	fmt "fmt"
	common "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for StockDetailService service

func NewStockDetailServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for StockDetailService service

type StockDetailService interface {
	Create(ctx context.Context, in *StockDetail, opts ...client.CallOption) (*StockDetailResponse, error)
	Update(ctx context.Context, in *StockDetail, opts ...client.CallOption) (*StockDetailResponse, error)
	Delete(ctx context.Context, in *StockDetail, opts ...client.CallOption) (*StockDetailResponse, error)
	Get(ctx context.Context, in *StockDetail, opts ...client.CallOption) (*StockDetailResponse, error)
	Search(ctx context.Context, in *common.BaseWhere, opts ...client.CallOption) (*StockDetailResponse, error)
}

type stockDetailService struct {
	c    client.Client
	name string
}

func NewStockDetailService(name string, c client.Client) StockDetailService {
	return &stockDetailService{
		c:    c,
		name: name,
	}
}

func (c *stockDetailService) Create(ctx context.Context, in *StockDetail, opts ...client.CallOption) (*StockDetailResponse, error) {
	req := c.c.NewRequest(c.name, "StockDetailService.Create", in)
	out := new(StockDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockDetailService) Update(ctx context.Context, in *StockDetail, opts ...client.CallOption) (*StockDetailResponse, error) {
	req := c.c.NewRequest(c.name, "StockDetailService.Update", in)
	out := new(StockDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockDetailService) Delete(ctx context.Context, in *StockDetail, opts ...client.CallOption) (*StockDetailResponse, error) {
	req := c.c.NewRequest(c.name, "StockDetailService.Delete", in)
	out := new(StockDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockDetailService) Get(ctx context.Context, in *StockDetail, opts ...client.CallOption) (*StockDetailResponse, error) {
	req := c.c.NewRequest(c.name, "StockDetailService.Get", in)
	out := new(StockDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockDetailService) Search(ctx context.Context, in *common.BaseWhere, opts ...client.CallOption) (*StockDetailResponse, error) {
	req := c.c.NewRequest(c.name, "StockDetailService.Search", in)
	out := new(StockDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StockDetailService service

type StockDetailServiceHandler interface {
	Create(context.Context, *StockDetail, *StockDetailResponse) error
	Update(context.Context, *StockDetail, *StockDetailResponse) error
	Delete(context.Context, *StockDetail, *StockDetailResponse) error
	Get(context.Context, *StockDetail, *StockDetailResponse) error
	Search(context.Context, *common.BaseWhere, *StockDetailResponse) error
}

func RegisterStockDetailServiceHandler(s server.Server, hdlr StockDetailServiceHandler, opts ...server.HandlerOption) error {
	type stockDetailService interface {
		Create(ctx context.Context, in *StockDetail, out *StockDetailResponse) error
		Update(ctx context.Context, in *StockDetail, out *StockDetailResponse) error
		Delete(ctx context.Context, in *StockDetail, out *StockDetailResponse) error
		Get(ctx context.Context, in *StockDetail, out *StockDetailResponse) error
		Search(ctx context.Context, in *common.BaseWhere, out *StockDetailResponse) error
	}
	type StockDetailService struct {
		stockDetailService
	}
	h := &stockDetailServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&StockDetailService{h}, opts...))
}

type stockDetailServiceHandler struct {
	StockDetailServiceHandler
}

func (h *stockDetailServiceHandler) Create(ctx context.Context, in *StockDetail, out *StockDetailResponse) error {
	return h.StockDetailServiceHandler.Create(ctx, in, out)
}

func (h *stockDetailServiceHandler) Update(ctx context.Context, in *StockDetail, out *StockDetailResponse) error {
	return h.StockDetailServiceHandler.Update(ctx, in, out)
}

func (h *stockDetailServiceHandler) Delete(ctx context.Context, in *StockDetail, out *StockDetailResponse) error {
	return h.StockDetailServiceHandler.Delete(ctx, in, out)
}

func (h *stockDetailServiceHandler) Get(ctx context.Context, in *StockDetail, out *StockDetailResponse) error {
	return h.StockDetailServiceHandler.Get(ctx, in, out)
}

func (h *stockDetailServiceHandler) Search(ctx context.Context, in *common.BaseWhere, out *StockDetailResponse) error {
	return h.StockDetailServiceHandler.Search(ctx, in, out)
}
