// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: myCapitalService.proto

package services

import (
	_ "github.com/geiqin/micro-kit/protobuf/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MyCapitalService service

func NewMyCapitalServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MyCapitalService service

type MyCapitalService interface {
	//提交充值订单
	Submit(ctx context.Context, in *CapitalRequest, opts ...client.CallOption) (*OrderResponse, error)
}

type myCapitalService struct {
	c    client.Client
	name string
}

func NewMyCapitalService(name string, c client.Client) MyCapitalService {
	return &myCapitalService{
		c:    c,
		name: name,
	}
}

func (c *myCapitalService) Submit(ctx context.Context, in *CapitalRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "MyCapitalService.Submit", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MyCapitalService service

type MyCapitalServiceHandler interface {
	//提交充值订单
	Submit(context.Context, *CapitalRequest, *OrderResponse) error
}

func RegisterMyCapitalServiceHandler(s server.Server, hdlr MyCapitalServiceHandler, opts ...server.HandlerOption) error {
	type myCapitalService interface {
		Submit(ctx context.Context, in *CapitalRequest, out *OrderResponse) error
	}
	type MyCapitalService struct {
		myCapitalService
	}
	h := &myCapitalServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&MyCapitalService{h}, opts...))
}

type myCapitalServiceHandler struct {
	MyCapitalServiceHandler
}

func (h *myCapitalServiceHandler) Submit(ctx context.Context, in *CapitalRequest, out *OrderResponse) error {
	return h.MyCapitalServiceHandler.Submit(ctx, in, out)
}
