// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: purchaseService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PurchaseService service

func NewPurchaseServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PurchaseService service

type PurchaseService interface {
	//填写订单
	Write(ctx context.Context, in *PurchaseRequest, opts ...client.CallOption) (*PurchaseResponse, error)
	//提交订单
	Submit(ctx context.Context, in *PurchaseRequest, opts ...client.CallOption) (*OrderResponse, error)
	//充值下单
	Recharge(ctx context.Context, in *PurchaseRequest, opts ...client.CallOption) (*OrderResponse, error)
}

type purchaseService struct {
	c    client.Client
	name string
}

func NewPurchaseService(name string, c client.Client) PurchaseService {
	return &purchaseService{
		c:    c,
		name: name,
	}
}

func (c *purchaseService) Write(ctx context.Context, in *PurchaseRequest, opts ...client.CallOption) (*PurchaseResponse, error) {
	req := c.c.NewRequest(c.name, "PurchaseService.Write", in)
	out := new(PurchaseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseService) Submit(ctx context.Context, in *PurchaseRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "PurchaseService.Submit", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseService) Recharge(ctx context.Context, in *PurchaseRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "PurchaseService.Recharge", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PurchaseService service

type PurchaseServiceHandler interface {
	//填写订单
	Write(context.Context, *PurchaseRequest, *PurchaseResponse) error
	//提交订单
	Submit(context.Context, *PurchaseRequest, *OrderResponse) error
	//充值下单
	Recharge(context.Context, *PurchaseRequest, *OrderResponse) error
}

func RegisterPurchaseServiceHandler(s server.Server, hdlr PurchaseServiceHandler, opts ...server.HandlerOption) error {
	type purchaseService interface {
		Write(ctx context.Context, in *PurchaseRequest, out *PurchaseResponse) error
		Submit(ctx context.Context, in *PurchaseRequest, out *OrderResponse) error
		Recharge(ctx context.Context, in *PurchaseRequest, out *OrderResponse) error
	}
	type PurchaseService struct {
		purchaseService
	}
	h := &purchaseServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PurchaseService{h}, opts...))
}

type purchaseServiceHandler struct {
	PurchaseServiceHandler
}

func (h *purchaseServiceHandler) Write(ctx context.Context, in *PurchaseRequest, out *PurchaseResponse) error {
	return h.PurchaseServiceHandler.Write(ctx, in, out)
}

func (h *purchaseServiceHandler) Submit(ctx context.Context, in *PurchaseRequest, out *OrderResponse) error {
	return h.PurchaseServiceHandler.Submit(ctx, in, out)
}

func (h *purchaseServiceHandler) Recharge(ctx context.Context, in *PurchaseRequest, out *OrderResponse) error {
	return h.PurchaseServiceHandler.Recharge(ctx, in, out)
}
