// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: posterService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PosterService service

func NewPosterServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PosterService service

type PosterService interface {
	Get(ctx context.Context, in *Poster, opts ...client.CallOption) (*PosterResponse, error)
	Save(ctx context.Context, in *Poster, opts ...client.CallOption) (*PosterResponse, error)
}

type posterService struct {
	c    client.Client
	name string
}

func NewPosterService(name string, c client.Client) PosterService {
	return &posterService{
		c:    c,
		name: name,
	}
}

func (c *posterService) Get(ctx context.Context, in *Poster, opts ...client.CallOption) (*PosterResponse, error) {
	req := c.c.NewRequest(c.name, "PosterService.Get", in)
	out := new(PosterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *posterService) Save(ctx context.Context, in *Poster, opts ...client.CallOption) (*PosterResponse, error) {
	req := c.c.NewRequest(c.name, "PosterService.Save", in)
	out := new(PosterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PosterService service

type PosterServiceHandler interface {
	Get(context.Context, *Poster, *PosterResponse) error
	Save(context.Context, *Poster, *PosterResponse) error
}

func RegisterPosterServiceHandler(s server.Server, hdlr PosterServiceHandler, opts ...server.HandlerOption) error {
	type posterService interface {
		Get(ctx context.Context, in *Poster, out *PosterResponse) error
		Save(ctx context.Context, in *Poster, out *PosterResponse) error
	}
	type PosterService struct {
		posterService
	}
	h := &posterServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PosterService{h}, opts...))
}

type posterServiceHandler struct {
	PosterServiceHandler
}

func (h *posterServiceHandler) Get(ctx context.Context, in *Poster, out *PosterResponse) error {
	return h.PosterServiceHandler.Get(ctx, in, out)
}

func (h *posterServiceHandler) Save(ctx context.Context, in *Poster, out *PosterResponse) error {
	return h.PosterServiceHandler.Save(ctx, in, out)
}

// Api Endpoints for FrontPosterService service

func NewFrontPosterServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for FrontPosterService service

type FrontPosterService interface {
	Get(ctx context.Context, in *Poster, opts ...client.CallOption) (*PosterResponse, error)
}

type frontPosterService struct {
	c    client.Client
	name string
}

func NewFrontPosterService(name string, c client.Client) FrontPosterService {
	return &frontPosterService{
		c:    c,
		name: name,
	}
}

func (c *frontPosterService) Get(ctx context.Context, in *Poster, opts ...client.CallOption) (*PosterResponse, error) {
	req := c.c.NewRequest(c.name, "FrontPosterService.Get", in)
	out := new(PosterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FrontPosterService service

type FrontPosterServiceHandler interface {
	Get(context.Context, *Poster, *PosterResponse) error
}

func RegisterFrontPosterServiceHandler(s server.Server, hdlr FrontPosterServiceHandler, opts ...server.HandlerOption) error {
	type frontPosterService interface {
		Get(ctx context.Context, in *Poster, out *PosterResponse) error
	}
	type FrontPosterService struct {
		frontPosterService
	}
	h := &frontPosterServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&FrontPosterService{h}, opts...))
}

type frontPosterServiceHandler struct {
	FrontPosterServiceHandler
}

func (h *frontPosterServiceHandler) Get(ctx context.Context, in *Poster, out *PosterResponse) error {
	return h.FrontPosterServiceHandler.Get(ctx, in, out)
}
