// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: accessLogisticsService.proto

package services

import (
	common "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AccessLogistics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogisticsNo string `protobuf:"bytes,1,opt,name=logistics_no,json=logisticsNo,proto3" json:"logistics_no"`
}

func (x *AccessLogistics) Reset() {
	*x = AccessLogistics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accessLogisticsService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessLogistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLogistics) ProtoMessage() {}

func (x *AccessLogistics) ProtoReflect() protoreflect.Message {
	mi := &file_accessLogisticsService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLogistics.ProtoReflect.Descriptor instead.
func (*AccessLogistics) Descriptor() ([]byte, []int) {
	return file_accessLogisticsService_proto_rawDescGZIP(), []int{0}
}

func (x *AccessLogistics) GetLogisticsNo() string {
	if x != nil {
		return x.LogisticsNo
	}
	return ""
}

type AccessLogisticsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShipperId  int32  `protobuf:"varint,1,opt,name=shipper_id,json=shipperId,proto3" json:"shipper_id"`
	OrderId    int64  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id"`
	DeliverySn string `protobuf:"bytes,3,opt,name=delivery_sn,json=deliverySn,proto3" json:"delivery_sn"`
	// @inject_tag: gorm:"-"
	Details []*AccessLogisticsDetailReq `protobuf:"bytes,4,rep,name=details,proto3" json:"details" gorm:"-"`
}

func (x *AccessLogisticsReq) Reset() {
	*x = AccessLogisticsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accessLogisticsService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessLogisticsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLogisticsReq) ProtoMessage() {}

func (x *AccessLogisticsReq) ProtoReflect() protoreflect.Message {
	mi := &file_accessLogisticsService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLogisticsReq.ProtoReflect.Descriptor instead.
func (*AccessLogisticsReq) Descriptor() ([]byte, []int) {
	return file_accessLogisticsService_proto_rawDescGZIP(), []int{1}
}

func (x *AccessLogisticsReq) GetShipperId() int32 {
	if x != nil {
		return x.ShipperId
	}
	return 0
}

func (x *AccessLogisticsReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *AccessLogisticsReq) GetDeliverySn() string {
	if x != nil {
		return x.DeliverySn
	}
	return ""
}

func (x *AccessLogisticsReq) GetDetails() []*AccessLogisticsDetailReq {
	if x != nil {
		return x.Details
	}
	return nil
}

type AccessLogisticsDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderDetailId int64 `protobuf:"varint,1,opt,name=order_detail_id,json=orderDetailId,proto3" json:"order_detail_id"`
	ItemId        int64 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id"`
	SkuId         int64 `protobuf:"varint,3,opt,name=sku_id,json=skuId,proto3" json:"sku_id"`
	Num           int32 `protobuf:"varint,4,opt,name=num,proto3" json:"num"`
}

func (x *AccessLogisticsDetailReq) Reset() {
	*x = AccessLogisticsDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accessLogisticsService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessLogisticsDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLogisticsDetailReq) ProtoMessage() {}

func (x *AccessLogisticsDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_accessLogisticsService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLogisticsDetailReq.ProtoReflect.Descriptor instead.
func (*AccessLogisticsDetailReq) Descriptor() ([]byte, []int) {
	return file_accessLogisticsService_proto_rawDescGZIP(), []int{2}
}

func (x *AccessLogisticsDetailReq) GetOrderDetailId() int64 {
	if x != nil {
		return x.OrderDetailId
	}
	return 0
}

func (x *AccessLogisticsDetailReq) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *AccessLogisticsDetailReq) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *AccessLogisticsDetailReq) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type AccessLogisticsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity *AccessLogistics   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity"`
	Pager  *common.Pager      `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager"`
	Items  []*AccessLogistics `protobuf:"bytes,3,rep,name=items,proto3" json:"items"`
	Error  *common.Error      `protobuf:"bytes,4,opt,name=error,proto3" json:"error"`
	Info   *common.Info       `protobuf:"bytes,5,opt,name=info,proto3" json:"info"`
}

func (x *AccessLogisticsResponse) Reset() {
	*x = AccessLogisticsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accessLogisticsService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessLogisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLogisticsResponse) ProtoMessage() {}

func (x *AccessLogisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accessLogisticsService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLogisticsResponse.ProtoReflect.Descriptor instead.
func (*AccessLogisticsResponse) Descriptor() ([]byte, []int) {
	return file_accessLogisticsService_proto_rawDescGZIP(), []int{3}
}

func (x *AccessLogisticsResponse) GetEntity() *AccessLogistics {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *AccessLogisticsResponse) GetPager() *common.Pager {
	if x != nil {
		return x.Pager
	}
	return nil
}

func (x *AccessLogisticsResponse) GetItems() []*AccessLogistics {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AccessLogisticsResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AccessLogisticsResponse) GetInfo() *common.Info {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_accessLogisticsService_proto protoreflect.FileDescriptor

var file_accessLogisticsService_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x0f, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x21,
	0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x6e, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x4e,
	0x6f, 0x22, 0xad, 0x01, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x69, 0x70,
	0x70, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x68,
	0x69, 0x70, 0x70, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x73,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x53, 0x6e, 0x12, 0x3c, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x22, 0x84, 0x01, 0x0a, 0x18, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x26,
	0x0a, 0x0f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12,
	0x15, 0x0a, 0x06, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x73, 0x6b, 0x75, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0xe9, 0x01, 0x0a, 0x17, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52,
	0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x23, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x20, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x32, 0x65, 0x0a, 0x16, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f,
	0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b,
	0x0a, 0x06, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x12, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_accessLogisticsService_proto_rawDescOnce sync.Once
	file_accessLogisticsService_proto_rawDescData = file_accessLogisticsService_proto_rawDesc
)

func file_accessLogisticsService_proto_rawDescGZIP() []byte {
	file_accessLogisticsService_proto_rawDescOnce.Do(func() {
		file_accessLogisticsService_proto_rawDescData = protoimpl.X.CompressGZIP(file_accessLogisticsService_proto_rawDescData)
	})
	return file_accessLogisticsService_proto_rawDescData
}

var file_accessLogisticsService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_accessLogisticsService_proto_goTypes = []interface{}{
	(*AccessLogistics)(nil),          // 0: services.AccessLogistics
	(*AccessLogisticsReq)(nil),       // 1: services.AccessLogisticsReq
	(*AccessLogisticsDetailReq)(nil), // 2: services.AccessLogisticsDetailReq
	(*AccessLogisticsResponse)(nil),  // 3: services.AccessLogisticsResponse
	(*common.Pager)(nil),             // 4: common.Pager
	(*common.Error)(nil),             // 5: common.Error
	(*common.Info)(nil),              // 6: common.Info
}
var file_accessLogisticsService_proto_depIdxs = []int32{
	2, // 0: services.AccessLogisticsReq.details:type_name -> services.AccessLogisticsDetailReq
	0, // 1: services.AccessLogisticsResponse.entity:type_name -> services.AccessLogistics
	4, // 2: services.AccessLogisticsResponse.pager:type_name -> common.Pager
	0, // 3: services.AccessLogisticsResponse.items:type_name -> services.AccessLogistics
	5, // 4: services.AccessLogisticsResponse.error:type_name -> common.Error
	6, // 5: services.AccessLogisticsResponse.info:type_name -> common.Info
	1, // 6: services.AccessLogisticsService.Submit:input_type -> services.AccessLogisticsReq
	3, // 7: services.AccessLogisticsService.Submit:output_type -> services.AccessLogisticsResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_accessLogisticsService_proto_init() }
func file_accessLogisticsService_proto_init() {
	if File_accessLogisticsService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_accessLogisticsService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessLogistics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accessLogisticsService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessLogisticsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accessLogisticsService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessLogisticsDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accessLogisticsService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessLogisticsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_accessLogisticsService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accessLogisticsService_proto_goTypes,
		DependencyIndexes: file_accessLogisticsService_proto_depIdxs,
		MessageInfos:      file_accessLogisticsService_proto_msgTypes,
	}.Build()
	File_accessLogisticsService_proto = out.File
	file_accessLogisticsService_proto_rawDesc = nil
	file_accessLogisticsService_proto_goTypes = nil
	file_accessLogisticsService_proto_depIdxs = nil
}
