// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: shipmentService.proto

package services

import (
	fmt "fmt"
	common "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ShipmentService service

func NewShipmentServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ShipmentService service

type ShipmentService interface {
	// 主要用于执行之前发货单数据的迁移（接口不对外开放）
	Migrate(ctx context.Context, in *common.Empty, opts ...client.CallOption) (*ShipmentResponse, error)
	Create(ctx context.Context, in *Shipment, opts ...client.CallOption) (*ShipmentResponse, error)
	Update(ctx context.Context, in *Shipment, opts ...client.CallOption) (*ShipmentResponse, error)
	Get(ctx context.Context, in *ShipmentWhere, opts ...client.CallOption) (*ShipmentResponse, error)
	List(ctx context.Context, in *ShipmentWhere, opts ...client.CallOption) (*ShipmentResponse, error)
}

type shipmentService struct {
	c    client.Client
	name string
}

func NewShipmentService(name string, c client.Client) ShipmentService {
	return &shipmentService{
		c:    c,
		name: name,
	}
}

func (c *shipmentService) Migrate(ctx context.Context, in *common.Empty, opts ...client.CallOption) (*ShipmentResponse, error) {
	req := c.c.NewRequest(c.name, "ShipmentService.Migrate", in)
	out := new(ShipmentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipmentService) Create(ctx context.Context, in *Shipment, opts ...client.CallOption) (*ShipmentResponse, error) {
	req := c.c.NewRequest(c.name, "ShipmentService.Create", in)
	out := new(ShipmentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipmentService) Update(ctx context.Context, in *Shipment, opts ...client.CallOption) (*ShipmentResponse, error) {
	req := c.c.NewRequest(c.name, "ShipmentService.Update", in)
	out := new(ShipmentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipmentService) Get(ctx context.Context, in *ShipmentWhere, opts ...client.CallOption) (*ShipmentResponse, error) {
	req := c.c.NewRequest(c.name, "ShipmentService.Get", in)
	out := new(ShipmentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipmentService) List(ctx context.Context, in *ShipmentWhere, opts ...client.CallOption) (*ShipmentResponse, error) {
	req := c.c.NewRequest(c.name, "ShipmentService.List", in)
	out := new(ShipmentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShipmentService service

type ShipmentServiceHandler interface {
	// 主要用于执行之前发货单数据的迁移（接口不对外开放）
	Migrate(context.Context, *common.Empty, *ShipmentResponse) error
	Create(context.Context, *Shipment, *ShipmentResponse) error
	Update(context.Context, *Shipment, *ShipmentResponse) error
	Get(context.Context, *ShipmentWhere, *ShipmentResponse) error
	List(context.Context, *ShipmentWhere, *ShipmentResponse) error
}

func RegisterShipmentServiceHandler(s server.Server, hdlr ShipmentServiceHandler, opts ...server.HandlerOption) error {
	type shipmentService interface {
		Migrate(ctx context.Context, in *common.Empty, out *ShipmentResponse) error
		Create(ctx context.Context, in *Shipment, out *ShipmentResponse) error
		Update(ctx context.Context, in *Shipment, out *ShipmentResponse) error
		Get(ctx context.Context, in *ShipmentWhere, out *ShipmentResponse) error
		List(ctx context.Context, in *ShipmentWhere, out *ShipmentResponse) error
	}
	type ShipmentService struct {
		shipmentService
	}
	h := &shipmentServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ShipmentService{h}, opts...))
}

type shipmentServiceHandler struct {
	ShipmentServiceHandler
}

func (h *shipmentServiceHandler) Migrate(ctx context.Context, in *common.Empty, out *ShipmentResponse) error {
	return h.ShipmentServiceHandler.Migrate(ctx, in, out)
}

func (h *shipmentServiceHandler) Create(ctx context.Context, in *Shipment, out *ShipmentResponse) error {
	return h.ShipmentServiceHandler.Create(ctx, in, out)
}

func (h *shipmentServiceHandler) Update(ctx context.Context, in *Shipment, out *ShipmentResponse) error {
	return h.ShipmentServiceHandler.Update(ctx, in, out)
}

func (h *shipmentServiceHandler) Get(ctx context.Context, in *ShipmentWhere, out *ShipmentResponse) error {
	return h.ShipmentServiceHandler.Get(ctx, in, out)
}

func (h *shipmentServiceHandler) List(ctx context.Context, in *ShipmentWhere, out *ShipmentResponse) error {
	return h.ShipmentServiceHandler.List(ctx, in, out)
}
