// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: authorizeService.proto

package services

import (
	fmt "fmt"
	common "github.com/geiqin/microkit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AuthorizeService service

func NewAuthorizeServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AuthorizeService service

type AuthorizeService interface {
	//微信小程序登录
	WxMini(ctx context.Context, in *WxMiniRequest, opts ...client.CallOption) (*common.TokenResponse, error)
	//微信三方授权登录
	WxAuth(ctx context.Context, in *AuthRequest, opts ...client.CallOption) (*common.TokenResponse, error)
	//支付宝授权登陆
	Alipay(ctx context.Context, in *AuthRequest, opts ...client.CallOption) (*common.TokenResponse, error)
}

type authorizeService struct {
	c    client.Client
	name string
}

func NewAuthorizeService(name string, c client.Client) AuthorizeService {
	return &authorizeService{
		c:    c,
		name: name,
	}
}

func (c *authorizeService) WxMini(ctx context.Context, in *WxMiniRequest, opts ...client.CallOption) (*common.TokenResponse, error) {
	req := c.c.NewRequest(c.name, "AuthorizeService.WxMini", in)
	out := new(common.TokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeService) WxAuth(ctx context.Context, in *AuthRequest, opts ...client.CallOption) (*common.TokenResponse, error) {
	req := c.c.NewRequest(c.name, "AuthorizeService.WxAuth", in)
	out := new(common.TokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeService) Alipay(ctx context.Context, in *AuthRequest, opts ...client.CallOption) (*common.TokenResponse, error) {
	req := c.c.NewRequest(c.name, "AuthorizeService.Alipay", in)
	out := new(common.TokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthorizeService service

type AuthorizeServiceHandler interface {
	//微信小程序登录
	WxMini(context.Context, *WxMiniRequest, *common.TokenResponse) error
	//微信三方授权登录
	WxAuth(context.Context, *AuthRequest, *common.TokenResponse) error
	//支付宝授权登陆
	Alipay(context.Context, *AuthRequest, *common.TokenResponse) error
}

func RegisterAuthorizeServiceHandler(s server.Server, hdlr AuthorizeServiceHandler, opts ...server.HandlerOption) error {
	type authorizeService interface {
		WxMini(ctx context.Context, in *WxMiniRequest, out *common.TokenResponse) error
		WxAuth(ctx context.Context, in *AuthRequest, out *common.TokenResponse) error
		Alipay(ctx context.Context, in *AuthRequest, out *common.TokenResponse) error
	}
	type AuthorizeService struct {
		authorizeService
	}
	h := &authorizeServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AuthorizeService{h}, opts...))
}

type authorizeServiceHandler struct {
	AuthorizeServiceHandler
}

func (h *authorizeServiceHandler) WxMini(ctx context.Context, in *WxMiniRequest, out *common.TokenResponse) error {
	return h.AuthorizeServiceHandler.WxMini(ctx, in, out)
}

func (h *authorizeServiceHandler) WxAuth(ctx context.Context, in *AuthRequest, out *common.TokenResponse) error {
	return h.AuthorizeServiceHandler.WxAuth(ctx, in, out)
}

func (h *authorizeServiceHandler) Alipay(ctx context.Context, in *AuthRequest, out *common.TokenResponse) error {
	return h.AuthorizeServiceHandler.Alipay(ctx, in, out)
}
