// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: dictTypeService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for DictTypeService service

func NewDictTypeServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for DictTypeService service

type DictTypeService interface {
	Create(ctx context.Context, in *DictType, opts ...client.CallOption) (*DictTypeResponse, error)
	Update(ctx context.Context, in *DictType, opts ...client.CallOption) (*DictTypeResponse, error)
	Delete(ctx context.Context, in *DictTypeRequest, opts ...client.CallOption) (*DictTypeResponse, error)
	Get(ctx context.Context, in *DictTypeRequest, opts ...client.CallOption) (*DictTypeResponse, error)
	Search(ctx context.Context, in *DictTypeRequest, opts ...client.CallOption) (*DictTypeResponse, error)
	List(ctx context.Context, in *DictTypeRequest, opts ...client.CallOption) (*DictTypeResponse, error)
	Dictionary(ctx context.Context, in *DictTypeRequest, opts ...client.CallOption) (*DictTypeResponse, error)
	SetStatus(ctx context.Context, in *DictTypeRequest, opts ...client.CallOption) (*DictTypeResponse, error)
}

type dictTypeService struct {
	c    client.Client
	name string
}

func NewDictTypeService(name string, c client.Client) DictTypeService {
	return &dictTypeService{
		c:    c,
		name: name,
	}
}

func (c *dictTypeService) Create(ctx context.Context, in *DictType, opts ...client.CallOption) (*DictTypeResponse, error) {
	req := c.c.NewRequest(c.name, "DictTypeService.Create", in)
	out := new(DictTypeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictTypeService) Update(ctx context.Context, in *DictType, opts ...client.CallOption) (*DictTypeResponse, error) {
	req := c.c.NewRequest(c.name, "DictTypeService.Update", in)
	out := new(DictTypeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictTypeService) Delete(ctx context.Context, in *DictTypeRequest, opts ...client.CallOption) (*DictTypeResponse, error) {
	req := c.c.NewRequest(c.name, "DictTypeService.Delete", in)
	out := new(DictTypeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictTypeService) Get(ctx context.Context, in *DictTypeRequest, opts ...client.CallOption) (*DictTypeResponse, error) {
	req := c.c.NewRequest(c.name, "DictTypeService.Get", in)
	out := new(DictTypeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictTypeService) Search(ctx context.Context, in *DictTypeRequest, opts ...client.CallOption) (*DictTypeResponse, error) {
	req := c.c.NewRequest(c.name, "DictTypeService.Search", in)
	out := new(DictTypeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictTypeService) List(ctx context.Context, in *DictTypeRequest, opts ...client.CallOption) (*DictTypeResponse, error) {
	req := c.c.NewRequest(c.name, "DictTypeService.List", in)
	out := new(DictTypeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictTypeService) Dictionary(ctx context.Context, in *DictTypeRequest, opts ...client.CallOption) (*DictTypeResponse, error) {
	req := c.c.NewRequest(c.name, "DictTypeService.Dictionary", in)
	out := new(DictTypeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictTypeService) SetStatus(ctx context.Context, in *DictTypeRequest, opts ...client.CallOption) (*DictTypeResponse, error) {
	req := c.c.NewRequest(c.name, "DictTypeService.SetStatus", in)
	out := new(DictTypeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DictTypeService service

type DictTypeServiceHandler interface {
	Create(context.Context, *DictType, *DictTypeResponse) error
	Update(context.Context, *DictType, *DictTypeResponse) error
	Delete(context.Context, *DictTypeRequest, *DictTypeResponse) error
	Get(context.Context, *DictTypeRequest, *DictTypeResponse) error
	Search(context.Context, *DictTypeRequest, *DictTypeResponse) error
	List(context.Context, *DictTypeRequest, *DictTypeResponse) error
	Dictionary(context.Context, *DictTypeRequest, *DictTypeResponse) error
	SetStatus(context.Context, *DictTypeRequest, *DictTypeResponse) error
}

func RegisterDictTypeServiceHandler(s server.Server, hdlr DictTypeServiceHandler, opts ...server.HandlerOption) error {
	type dictTypeService interface {
		Create(ctx context.Context, in *DictType, out *DictTypeResponse) error
		Update(ctx context.Context, in *DictType, out *DictTypeResponse) error
		Delete(ctx context.Context, in *DictTypeRequest, out *DictTypeResponse) error
		Get(ctx context.Context, in *DictTypeRequest, out *DictTypeResponse) error
		Search(ctx context.Context, in *DictTypeRequest, out *DictTypeResponse) error
		List(ctx context.Context, in *DictTypeRequest, out *DictTypeResponse) error
		Dictionary(ctx context.Context, in *DictTypeRequest, out *DictTypeResponse) error
		SetStatus(ctx context.Context, in *DictTypeRequest, out *DictTypeResponse) error
	}
	type DictTypeService struct {
		dictTypeService
	}
	h := &dictTypeServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&DictTypeService{h}, opts...))
}

type dictTypeServiceHandler struct {
	DictTypeServiceHandler
}

func (h *dictTypeServiceHandler) Create(ctx context.Context, in *DictType, out *DictTypeResponse) error {
	return h.DictTypeServiceHandler.Create(ctx, in, out)
}

func (h *dictTypeServiceHandler) Update(ctx context.Context, in *DictType, out *DictTypeResponse) error {
	return h.DictTypeServiceHandler.Update(ctx, in, out)
}

func (h *dictTypeServiceHandler) Delete(ctx context.Context, in *DictTypeRequest, out *DictTypeResponse) error {
	return h.DictTypeServiceHandler.Delete(ctx, in, out)
}

func (h *dictTypeServiceHandler) Get(ctx context.Context, in *DictTypeRequest, out *DictTypeResponse) error {
	return h.DictTypeServiceHandler.Get(ctx, in, out)
}

func (h *dictTypeServiceHandler) Search(ctx context.Context, in *DictTypeRequest, out *DictTypeResponse) error {
	return h.DictTypeServiceHandler.Search(ctx, in, out)
}

func (h *dictTypeServiceHandler) List(ctx context.Context, in *DictTypeRequest, out *DictTypeResponse) error {
	return h.DictTypeServiceHandler.List(ctx, in, out)
}

func (h *dictTypeServiceHandler) Dictionary(ctx context.Context, in *DictTypeRequest, out *DictTypeResponse) error {
	return h.DictTypeServiceHandler.Dictionary(ctx, in, out)
}

func (h *dictTypeServiceHandler) SetStatus(ctx context.Context, in *DictTypeRequest, out *DictTypeResponse) error {
	return h.DictTypeServiceHandler.SetStatus(ctx, in, out)
}
