// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: mobileSettingService.proto

package services

import (
	fmt "fmt"
	common "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MobileSettingService service

func NewMobileSettingServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MobileSettingService service

type MobileSettingService interface {
	Set(ctx context.Context, in *MobileSetting, opts ...client.CallOption) (*MobileSettingResponse, error)
	Get(ctx context.Context, in *common.Empty, opts ...client.CallOption) (*MobileSettingResponse, error)
}

type mobileSettingService struct {
	c    client.Client
	name string
}

func NewMobileSettingService(name string, c client.Client) MobileSettingService {
	return &mobileSettingService{
		c:    c,
		name: name,
	}
}

func (c *mobileSettingService) Set(ctx context.Context, in *MobileSetting, opts ...client.CallOption) (*MobileSettingResponse, error) {
	req := c.c.NewRequest(c.name, "MobileSettingService.Set", in)
	out := new(MobileSettingResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mobileSettingService) Get(ctx context.Context, in *common.Empty, opts ...client.CallOption) (*MobileSettingResponse, error) {
	req := c.c.NewRequest(c.name, "MobileSettingService.Get", in)
	out := new(MobileSettingResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MobileSettingService service

type MobileSettingServiceHandler interface {
	Set(context.Context, *MobileSetting, *MobileSettingResponse) error
	Get(context.Context, *common.Empty, *MobileSettingResponse) error
}

func RegisterMobileSettingServiceHandler(s server.Server, hdlr MobileSettingServiceHandler, opts ...server.HandlerOption) error {
	type mobileSettingService interface {
		Set(ctx context.Context, in *MobileSetting, out *MobileSettingResponse) error
		Get(ctx context.Context, in *common.Empty, out *MobileSettingResponse) error
	}
	type MobileSettingService struct {
		mobileSettingService
	}
	h := &mobileSettingServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&MobileSettingService{h}, opts...))
}

type mobileSettingServiceHandler struct {
	MobileSettingServiceHandler
}

func (h *mobileSettingServiceHandler) Set(ctx context.Context, in *MobileSetting, out *MobileSettingResponse) error {
	return h.MobileSettingServiceHandler.Set(ctx, in, out)
}

func (h *mobileSettingServiceHandler) Get(ctx context.Context, in *common.Empty, out *MobileSettingResponse) error {
	return h.MobileSettingServiceHandler.Get(ctx, in, out)
}
