// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: posterService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PosterService service

func NewPosterServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PosterService service

type PosterService interface {
	Create(ctx context.Context, in *Poster, opts ...client.CallOption) (*PosterResponse, error)
	Update(ctx context.Context, in *Poster, opts ...client.CallOption) (*PosterResponse, error)
	Delete(ctx context.Context, in *PosterRequest, opts ...client.CallOption) (*PosterResponse, error)
	Get(ctx context.Context, in *Poster, opts ...client.CallOption) (*PosterResponse, error)
	Search(ctx context.Context, in *PosterRequest, opts ...client.CallOption) (*PosterResponse, error)
	Display(ctx context.Context, in *PosterRequest, opts ...client.CallOption) (*PosterResponse, error)
}

type posterService struct {
	c    client.Client
	name string
}

func NewPosterService(name string, c client.Client) PosterService {
	return &posterService{
		c:    c,
		name: name,
	}
}

func (c *posterService) Create(ctx context.Context, in *Poster, opts ...client.CallOption) (*PosterResponse, error) {
	req := c.c.NewRequest(c.name, "PosterService.Create", in)
	out := new(PosterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *posterService) Update(ctx context.Context, in *Poster, opts ...client.CallOption) (*PosterResponse, error) {
	req := c.c.NewRequest(c.name, "PosterService.Update", in)
	out := new(PosterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *posterService) Delete(ctx context.Context, in *PosterRequest, opts ...client.CallOption) (*PosterResponse, error) {
	req := c.c.NewRequest(c.name, "PosterService.Delete", in)
	out := new(PosterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *posterService) Get(ctx context.Context, in *Poster, opts ...client.CallOption) (*PosterResponse, error) {
	req := c.c.NewRequest(c.name, "PosterService.Get", in)
	out := new(PosterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *posterService) Search(ctx context.Context, in *PosterRequest, opts ...client.CallOption) (*PosterResponse, error) {
	req := c.c.NewRequest(c.name, "PosterService.Search", in)
	out := new(PosterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *posterService) Display(ctx context.Context, in *PosterRequest, opts ...client.CallOption) (*PosterResponse, error) {
	req := c.c.NewRequest(c.name, "PosterService.Display", in)
	out := new(PosterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PosterService service

type PosterServiceHandler interface {
	Create(context.Context, *Poster, *PosterResponse) error
	Update(context.Context, *Poster, *PosterResponse) error
	Delete(context.Context, *PosterRequest, *PosterResponse) error
	Get(context.Context, *Poster, *PosterResponse) error
	Search(context.Context, *PosterRequest, *PosterResponse) error
	Display(context.Context, *PosterRequest, *PosterResponse) error
}

func RegisterPosterServiceHandler(s server.Server, hdlr PosterServiceHandler, opts ...server.HandlerOption) error {
	type posterService interface {
		Create(ctx context.Context, in *Poster, out *PosterResponse) error
		Update(ctx context.Context, in *Poster, out *PosterResponse) error
		Delete(ctx context.Context, in *PosterRequest, out *PosterResponse) error
		Get(ctx context.Context, in *Poster, out *PosterResponse) error
		Search(ctx context.Context, in *PosterRequest, out *PosterResponse) error
		Display(ctx context.Context, in *PosterRequest, out *PosterResponse) error
	}
	type PosterService struct {
		posterService
	}
	h := &posterServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PosterService{h}, opts...))
}

type posterServiceHandler struct {
	PosterServiceHandler
}

func (h *posterServiceHandler) Create(ctx context.Context, in *Poster, out *PosterResponse) error {
	return h.PosterServiceHandler.Create(ctx, in, out)
}

func (h *posterServiceHandler) Update(ctx context.Context, in *Poster, out *PosterResponse) error {
	return h.PosterServiceHandler.Update(ctx, in, out)
}

func (h *posterServiceHandler) Delete(ctx context.Context, in *PosterRequest, out *PosterResponse) error {
	return h.PosterServiceHandler.Delete(ctx, in, out)
}

func (h *posterServiceHandler) Get(ctx context.Context, in *Poster, out *PosterResponse) error {
	return h.PosterServiceHandler.Get(ctx, in, out)
}

func (h *posterServiceHandler) Search(ctx context.Context, in *PosterRequest, out *PosterResponse) error {
	return h.PosterServiceHandler.Search(ctx, in, out)
}

func (h *posterServiceHandler) Display(ctx context.Context, in *PosterRequest, out *PosterResponse) error {
	return h.PosterServiceHandler.Display(ctx, in, out)
}
