// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: posterElementService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PosterElementService service

func NewPosterElementServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PosterElementService service

type PosterElementService interface {
	Create(ctx context.Context, in *PosterElement, opts ...client.CallOption) (*PosterElementResponse, error)
	Delete(ctx context.Context, in *PosterElement, opts ...client.CallOption) (*PosterElementResponse, error)
	Get(ctx context.Context, in *PosterElement, opts ...client.CallOption) (*PosterElementResponse, error)
	Search(ctx context.Context, in *PosterElementRequest, opts ...client.CallOption) (*PosterElementResponse, error)
}

type posterElementService struct {
	c    client.Client
	name string
}

func NewPosterElementService(name string, c client.Client) PosterElementService {
	return &posterElementService{
		c:    c,
		name: name,
	}
}

func (c *posterElementService) Create(ctx context.Context, in *PosterElement, opts ...client.CallOption) (*PosterElementResponse, error) {
	req := c.c.NewRequest(c.name, "PosterElementService.Create", in)
	out := new(PosterElementResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *posterElementService) Delete(ctx context.Context, in *PosterElement, opts ...client.CallOption) (*PosterElementResponse, error) {
	req := c.c.NewRequest(c.name, "PosterElementService.Delete", in)
	out := new(PosterElementResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *posterElementService) Get(ctx context.Context, in *PosterElement, opts ...client.CallOption) (*PosterElementResponse, error) {
	req := c.c.NewRequest(c.name, "PosterElementService.Get", in)
	out := new(PosterElementResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *posterElementService) Search(ctx context.Context, in *PosterElementRequest, opts ...client.CallOption) (*PosterElementResponse, error) {
	req := c.c.NewRequest(c.name, "PosterElementService.Search", in)
	out := new(PosterElementResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PosterElementService service

type PosterElementServiceHandler interface {
	Create(context.Context, *PosterElement, *PosterElementResponse) error
	Delete(context.Context, *PosterElement, *PosterElementResponse) error
	Get(context.Context, *PosterElement, *PosterElementResponse) error
	Search(context.Context, *PosterElementRequest, *PosterElementResponse) error
}

func RegisterPosterElementServiceHandler(s server.Server, hdlr PosterElementServiceHandler, opts ...server.HandlerOption) error {
	type posterElementService interface {
		Create(ctx context.Context, in *PosterElement, out *PosterElementResponse) error
		Delete(ctx context.Context, in *PosterElement, out *PosterElementResponse) error
		Get(ctx context.Context, in *PosterElement, out *PosterElementResponse) error
		Search(ctx context.Context, in *PosterElementRequest, out *PosterElementResponse) error
	}
	type PosterElementService struct {
		posterElementService
	}
	h := &posterElementServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PosterElementService{h}, opts...))
}

type posterElementServiceHandler struct {
	PosterElementServiceHandler
}

func (h *posterElementServiceHandler) Create(ctx context.Context, in *PosterElement, out *PosterElementResponse) error {
	return h.PosterElementServiceHandler.Create(ctx, in, out)
}

func (h *posterElementServiceHandler) Delete(ctx context.Context, in *PosterElement, out *PosterElementResponse) error {
	return h.PosterElementServiceHandler.Delete(ctx, in, out)
}

func (h *posterElementServiceHandler) Get(ctx context.Context, in *PosterElement, out *PosterElementResponse) error {
	return h.PosterElementServiceHandler.Get(ctx, in, out)
}

func (h *posterElementServiceHandler) Search(ctx context.Context, in *PosterElementRequest, out *PosterElementResponse) error {
	return h.PosterElementServiceHandler.Search(ctx, in, out)
}
