// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: settingService.proto

package services

import (
	fmt "fmt"
	common "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SettingService service

func NewSettingServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SettingService service

type SettingService interface {
	Get(ctx context.Context, in *Setting, opts ...client.CallOption) (*SettingResponse, error)
	Search(ctx context.Context, in *common.BaseWhere, opts ...client.CallOption) (*SettingResponse, error)
	List(ctx context.Context, in *Setting, opts ...client.CallOption) (*SettingResponse, error)
	Tree(ctx context.Context, in *Setting, opts ...client.CallOption) (*SettingResponse, error)
}

type settingService struct {
	c    client.Client
	name string
}

func NewSettingService(name string, c client.Client) SettingService {
	return &settingService{
		c:    c,
		name: name,
	}
}

func (c *settingService) Get(ctx context.Context, in *Setting, opts ...client.CallOption) (*SettingResponse, error) {
	req := c.c.NewRequest(c.name, "SettingService.Get", in)
	out := new(SettingResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingService) Search(ctx context.Context, in *common.BaseWhere, opts ...client.CallOption) (*SettingResponse, error) {
	req := c.c.NewRequest(c.name, "SettingService.Search", in)
	out := new(SettingResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingService) List(ctx context.Context, in *Setting, opts ...client.CallOption) (*SettingResponse, error) {
	req := c.c.NewRequest(c.name, "SettingService.List", in)
	out := new(SettingResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingService) Tree(ctx context.Context, in *Setting, opts ...client.CallOption) (*SettingResponse, error) {
	req := c.c.NewRequest(c.name, "SettingService.Tree", in)
	out := new(SettingResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SettingService service

type SettingServiceHandler interface {
	Get(context.Context, *Setting, *SettingResponse) error
	Search(context.Context, *common.BaseWhere, *SettingResponse) error
	List(context.Context, *Setting, *SettingResponse) error
	Tree(context.Context, *Setting, *SettingResponse) error
}

func RegisterSettingServiceHandler(s server.Server, hdlr SettingServiceHandler, opts ...server.HandlerOption) error {
	type settingService interface {
		Get(ctx context.Context, in *Setting, out *SettingResponse) error
		Search(ctx context.Context, in *common.BaseWhere, out *SettingResponse) error
		List(ctx context.Context, in *Setting, out *SettingResponse) error
		Tree(ctx context.Context, in *Setting, out *SettingResponse) error
	}
	type SettingService struct {
		settingService
	}
	h := &settingServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&SettingService{h}, opts...))
}

type settingServiceHandler struct {
	SettingServiceHandler
}

func (h *settingServiceHandler) Get(ctx context.Context, in *Setting, out *SettingResponse) error {
	return h.SettingServiceHandler.Get(ctx, in, out)
}

func (h *settingServiceHandler) Search(ctx context.Context, in *common.BaseWhere, out *SettingResponse) error {
	return h.SettingServiceHandler.Search(ctx, in, out)
}

func (h *settingServiceHandler) List(ctx context.Context, in *Setting, out *SettingResponse) error {
	return h.SettingServiceHandler.List(ctx, in, out)
}

func (h *settingServiceHandler) Tree(ctx context.Context, in *Setting, out *SettingResponse) error {
	return h.SettingServiceHandler.Tree(ctx, in, out)
}
