// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: versionService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for VersionService service

func NewVersionServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for VersionService service

type VersionService interface {
	Create(ctx context.Context, in *Version, opts ...client.CallOption) (*VersionResponse, error)
	Update(ctx context.Context, in *Version, opts ...client.CallOption) (*VersionResponse, error)
	Delete(ctx context.Context, in *Version, opts ...client.CallOption) (*VersionResponse, error)
	Get(ctx context.Context, in *Version, opts ...client.CallOption) (*VersionResponse, error)
	Search(ctx context.Context, in *VersionRequest, opts ...client.CallOption) (*VersionResponse, error)
	Master(ctx context.Context, in *Version, opts ...client.CallOption) (*VersionResponse, error)
}

type versionService struct {
	c    client.Client
	name string
}

func NewVersionService(name string, c client.Client) VersionService {
	return &versionService{
		c:    c,
		name: name,
	}
}

func (c *versionService) Create(ctx context.Context, in *Version, opts ...client.CallOption) (*VersionResponse, error) {
	req := c.c.NewRequest(c.name, "VersionService.Create", in)
	out := new(VersionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionService) Update(ctx context.Context, in *Version, opts ...client.CallOption) (*VersionResponse, error) {
	req := c.c.NewRequest(c.name, "VersionService.Update", in)
	out := new(VersionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionService) Delete(ctx context.Context, in *Version, opts ...client.CallOption) (*VersionResponse, error) {
	req := c.c.NewRequest(c.name, "VersionService.Delete", in)
	out := new(VersionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionService) Get(ctx context.Context, in *Version, opts ...client.CallOption) (*VersionResponse, error) {
	req := c.c.NewRequest(c.name, "VersionService.Get", in)
	out := new(VersionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionService) Search(ctx context.Context, in *VersionRequest, opts ...client.CallOption) (*VersionResponse, error) {
	req := c.c.NewRequest(c.name, "VersionService.Search", in)
	out := new(VersionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionService) Master(ctx context.Context, in *Version, opts ...client.CallOption) (*VersionResponse, error) {
	req := c.c.NewRequest(c.name, "VersionService.Master", in)
	out := new(VersionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VersionService service

type VersionServiceHandler interface {
	Create(context.Context, *Version, *VersionResponse) error
	Update(context.Context, *Version, *VersionResponse) error
	Delete(context.Context, *Version, *VersionResponse) error
	Get(context.Context, *Version, *VersionResponse) error
	Search(context.Context, *VersionRequest, *VersionResponse) error
	Master(context.Context, *Version, *VersionResponse) error
}

func RegisterVersionServiceHandler(s server.Server, hdlr VersionServiceHandler, opts ...server.HandlerOption) error {
	type versionService interface {
		Create(ctx context.Context, in *Version, out *VersionResponse) error
		Update(ctx context.Context, in *Version, out *VersionResponse) error
		Delete(ctx context.Context, in *Version, out *VersionResponse) error
		Get(ctx context.Context, in *Version, out *VersionResponse) error
		Search(ctx context.Context, in *VersionRequest, out *VersionResponse) error
		Master(ctx context.Context, in *Version, out *VersionResponse) error
	}
	type VersionService struct {
		versionService
	}
	h := &versionServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&VersionService{h}, opts...))
}

type versionServiceHandler struct {
	VersionServiceHandler
}

func (h *versionServiceHandler) Create(ctx context.Context, in *Version, out *VersionResponse) error {
	return h.VersionServiceHandler.Create(ctx, in, out)
}

func (h *versionServiceHandler) Update(ctx context.Context, in *Version, out *VersionResponse) error {
	return h.VersionServiceHandler.Update(ctx, in, out)
}

func (h *versionServiceHandler) Delete(ctx context.Context, in *Version, out *VersionResponse) error {
	return h.VersionServiceHandler.Delete(ctx, in, out)
}

func (h *versionServiceHandler) Get(ctx context.Context, in *Version, out *VersionResponse) error {
	return h.VersionServiceHandler.Get(ctx, in, out)
}

func (h *versionServiceHandler) Search(ctx context.Context, in *VersionRequest, out *VersionResponse) error {
	return h.VersionServiceHandler.Search(ctx, in, out)
}

func (h *versionServiceHandler) Master(ctx context.Context, in *Version, out *VersionResponse) error {
	return h.VersionServiceHandler.Master(ctx, in, out)
}
