// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: capitalSchemeService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CapitalSchemeService service

func NewCapitalSchemeServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CapitalSchemeService service

type CapitalSchemeService interface {
	//增加充值方案
	Create(ctx context.Context, in *CapitalScheme, opts ...client.CallOption) (*CapitalSchemeResponse, error)
	//修改充值方案
	Update(ctx context.Context, in *CapitalScheme, opts ...client.CallOption) (*CapitalSchemeResponse, error)
	//获得充值方案信息
	Get(ctx context.Context, in *CapitalScheme, opts ...client.CallOption) (*CapitalSchemeResponse, error)
	//查询充值方案信息
	Search(ctx context.Context, in *CapitalSchemeWhere, opts ...client.CallOption) (*CapitalSchemeResponse, error)
	//有效方案列表
	List(ctx context.Context, in *CapitalSchemeWhere, opts ...client.CallOption) (*CapitalSchemeResponse, error)
	//根据金额匹配最优方案
	Matching(ctx context.Context, in *CapitalSchemeWhere, opts ...client.CallOption) (*CapitalSchemeResponse, error)
}

type capitalSchemeService struct {
	c    client.Client
	name string
}

func NewCapitalSchemeService(name string, c client.Client) CapitalSchemeService {
	return &capitalSchemeService{
		c:    c,
		name: name,
	}
}

func (c *capitalSchemeService) Create(ctx context.Context, in *CapitalScheme, opts ...client.CallOption) (*CapitalSchemeResponse, error) {
	req := c.c.NewRequest(c.name, "CapitalSchemeService.Create", in)
	out := new(CapitalSchemeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capitalSchemeService) Update(ctx context.Context, in *CapitalScheme, opts ...client.CallOption) (*CapitalSchemeResponse, error) {
	req := c.c.NewRequest(c.name, "CapitalSchemeService.Update", in)
	out := new(CapitalSchemeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capitalSchemeService) Get(ctx context.Context, in *CapitalScheme, opts ...client.CallOption) (*CapitalSchemeResponse, error) {
	req := c.c.NewRequest(c.name, "CapitalSchemeService.Get", in)
	out := new(CapitalSchemeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capitalSchemeService) Search(ctx context.Context, in *CapitalSchemeWhere, opts ...client.CallOption) (*CapitalSchemeResponse, error) {
	req := c.c.NewRequest(c.name, "CapitalSchemeService.Search", in)
	out := new(CapitalSchemeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capitalSchemeService) List(ctx context.Context, in *CapitalSchemeWhere, opts ...client.CallOption) (*CapitalSchemeResponse, error) {
	req := c.c.NewRequest(c.name, "CapitalSchemeService.List", in)
	out := new(CapitalSchemeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capitalSchemeService) Matching(ctx context.Context, in *CapitalSchemeWhere, opts ...client.CallOption) (*CapitalSchemeResponse, error) {
	req := c.c.NewRequest(c.name, "CapitalSchemeService.Matching", in)
	out := new(CapitalSchemeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CapitalSchemeService service

type CapitalSchemeServiceHandler interface {
	//增加充值方案
	Create(context.Context, *CapitalScheme, *CapitalSchemeResponse) error
	//修改充值方案
	Update(context.Context, *CapitalScheme, *CapitalSchemeResponse) error
	//获得充值方案信息
	Get(context.Context, *CapitalScheme, *CapitalSchemeResponse) error
	//查询充值方案信息
	Search(context.Context, *CapitalSchemeWhere, *CapitalSchemeResponse) error
	//有效方案列表
	List(context.Context, *CapitalSchemeWhere, *CapitalSchemeResponse) error
	//根据金额匹配最优方案
	Matching(context.Context, *CapitalSchemeWhere, *CapitalSchemeResponse) error
}

func RegisterCapitalSchemeServiceHandler(s server.Server, hdlr CapitalSchemeServiceHandler, opts ...server.HandlerOption) error {
	type capitalSchemeService interface {
		Create(ctx context.Context, in *CapitalScheme, out *CapitalSchemeResponse) error
		Update(ctx context.Context, in *CapitalScheme, out *CapitalSchemeResponse) error
		Get(ctx context.Context, in *CapitalScheme, out *CapitalSchemeResponse) error
		Search(ctx context.Context, in *CapitalSchemeWhere, out *CapitalSchemeResponse) error
		List(ctx context.Context, in *CapitalSchemeWhere, out *CapitalSchemeResponse) error
		Matching(ctx context.Context, in *CapitalSchemeWhere, out *CapitalSchemeResponse) error
	}
	type CapitalSchemeService struct {
		capitalSchemeService
	}
	h := &capitalSchemeServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CapitalSchemeService{h}, opts...))
}

type capitalSchemeServiceHandler struct {
	CapitalSchemeServiceHandler
}

func (h *capitalSchemeServiceHandler) Create(ctx context.Context, in *CapitalScheme, out *CapitalSchemeResponse) error {
	return h.CapitalSchemeServiceHandler.Create(ctx, in, out)
}

func (h *capitalSchemeServiceHandler) Update(ctx context.Context, in *CapitalScheme, out *CapitalSchemeResponse) error {
	return h.CapitalSchemeServiceHandler.Update(ctx, in, out)
}

func (h *capitalSchemeServiceHandler) Get(ctx context.Context, in *CapitalScheme, out *CapitalSchemeResponse) error {
	return h.CapitalSchemeServiceHandler.Get(ctx, in, out)
}

func (h *capitalSchemeServiceHandler) Search(ctx context.Context, in *CapitalSchemeWhere, out *CapitalSchemeResponse) error {
	return h.CapitalSchemeServiceHandler.Search(ctx, in, out)
}

func (h *capitalSchemeServiceHandler) List(ctx context.Context, in *CapitalSchemeWhere, out *CapitalSchemeResponse) error {
	return h.CapitalSchemeServiceHandler.List(ctx, in, out)
}

func (h *capitalSchemeServiceHandler) Matching(ctx context.Context, in *CapitalSchemeWhere, out *CapitalSchemeResponse) error {
	return h.CapitalSchemeServiceHandler.Matching(ctx, in, out)
}
