// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: customerBankService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CustomerBankService service

func NewCustomerBankServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CustomerBankService service

type CustomerBankService interface {
	Create(ctx context.Context, in *CustomerBank, opts ...client.CallOption) (*CustomerBankResponse, error)
	Delete(ctx context.Context, in *CustomerBank, opts ...client.CallOption) (*CustomerBankResponse, error)
	Get(ctx context.Context, in *CustomerBank, opts ...client.CallOption) (*CustomerBankResponse, error)
	Search(ctx context.Context, in *CustomerBankRequest, opts ...client.CallOption) (*CustomerBankResponse, error)
}

type customerBankService struct {
	c    client.Client
	name string
}

func NewCustomerBankService(name string, c client.Client) CustomerBankService {
	return &customerBankService{
		c:    c,
		name: name,
	}
}

func (c *customerBankService) Create(ctx context.Context, in *CustomerBank, opts ...client.CallOption) (*CustomerBankResponse, error) {
	req := c.c.NewRequest(c.name, "CustomerBankService.Create", in)
	out := new(CustomerBankResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerBankService) Delete(ctx context.Context, in *CustomerBank, opts ...client.CallOption) (*CustomerBankResponse, error) {
	req := c.c.NewRequest(c.name, "CustomerBankService.Delete", in)
	out := new(CustomerBankResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerBankService) Get(ctx context.Context, in *CustomerBank, opts ...client.CallOption) (*CustomerBankResponse, error) {
	req := c.c.NewRequest(c.name, "CustomerBankService.Get", in)
	out := new(CustomerBankResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerBankService) Search(ctx context.Context, in *CustomerBankRequest, opts ...client.CallOption) (*CustomerBankResponse, error) {
	req := c.c.NewRequest(c.name, "CustomerBankService.Search", in)
	out := new(CustomerBankResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CustomerBankService service

type CustomerBankServiceHandler interface {
	Create(context.Context, *CustomerBank, *CustomerBankResponse) error
	Delete(context.Context, *CustomerBank, *CustomerBankResponse) error
	Get(context.Context, *CustomerBank, *CustomerBankResponse) error
	Search(context.Context, *CustomerBankRequest, *CustomerBankResponse) error
}

func RegisterCustomerBankServiceHandler(s server.Server, hdlr CustomerBankServiceHandler, opts ...server.HandlerOption) error {
	type customerBankService interface {
		Create(ctx context.Context, in *CustomerBank, out *CustomerBankResponse) error
		Delete(ctx context.Context, in *CustomerBank, out *CustomerBankResponse) error
		Get(ctx context.Context, in *CustomerBank, out *CustomerBankResponse) error
		Search(ctx context.Context, in *CustomerBankRequest, out *CustomerBankResponse) error
	}
	type CustomerBankService struct {
		customerBankService
	}
	h := &customerBankServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CustomerBankService{h}, opts...))
}

type customerBankServiceHandler struct {
	CustomerBankServiceHandler
}

func (h *customerBankServiceHandler) Create(ctx context.Context, in *CustomerBank, out *CustomerBankResponse) error {
	return h.CustomerBankServiceHandler.Create(ctx, in, out)
}

func (h *customerBankServiceHandler) Delete(ctx context.Context, in *CustomerBank, out *CustomerBankResponse) error {
	return h.CustomerBankServiceHandler.Delete(ctx, in, out)
}

func (h *customerBankServiceHandler) Get(ctx context.Context, in *CustomerBank, out *CustomerBankResponse) error {
	return h.CustomerBankServiceHandler.Get(ctx, in, out)
}

func (h *customerBankServiceHandler) Search(ctx context.Context, in *CustomerBankRequest, out *CustomerBankResponse) error {
	return h.CustomerBankServiceHandler.Search(ctx, in, out)
}
