// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: securityService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SecurityService service

func NewSecurityServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SecurityService service

type SecurityService interface {
	//判断有无密码保护
	HasPwd(ctx context.Context, in *SecurityRequest, opts ...client.CallOption) (*SecurityResponse, error)
	//创建密码(未设置密码前可用)
	CreatePwd(ctx context.Context, in *SecurityRequest, opts ...client.CallOption) (*SecurityResponse, error)
	//修改密码
	ModifyPwd(ctx context.Context, in *SecurityRequest, opts ...client.CallOption) (*SecurityResponse, error)
	//绑定手机号
	BindMobile(ctx context.Context, in *SecurityRequest, opts ...client.CallOption) (*SecurityResponse, error)
	//绑定邮箱
	BindEmail(ctx context.Context, in *SecurityRequest, opts ...client.CallOption) (*SecurityResponse, error)
	//绑定微信
	BindWx(ctx context.Context, in *SecurityRequest, opts ...client.CallOption) (*SecurityResponse, error)
	//注销账户
	Destroy(ctx context.Context, in *SecurityRequest, opts ...client.CallOption) (*SecurityResponse, error)
}

type securityService struct {
	c    client.Client
	name string
}

func NewSecurityService(name string, c client.Client) SecurityService {
	return &securityService{
		c:    c,
		name: name,
	}
}

func (c *securityService) HasPwd(ctx context.Context, in *SecurityRequest, opts ...client.CallOption) (*SecurityResponse, error) {
	req := c.c.NewRequest(c.name, "SecurityService.HasPwd", in)
	out := new(SecurityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityService) CreatePwd(ctx context.Context, in *SecurityRequest, opts ...client.CallOption) (*SecurityResponse, error) {
	req := c.c.NewRequest(c.name, "SecurityService.CreatePwd", in)
	out := new(SecurityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityService) ModifyPwd(ctx context.Context, in *SecurityRequest, opts ...client.CallOption) (*SecurityResponse, error) {
	req := c.c.NewRequest(c.name, "SecurityService.ModifyPwd", in)
	out := new(SecurityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityService) BindMobile(ctx context.Context, in *SecurityRequest, opts ...client.CallOption) (*SecurityResponse, error) {
	req := c.c.NewRequest(c.name, "SecurityService.BindMobile", in)
	out := new(SecurityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityService) BindEmail(ctx context.Context, in *SecurityRequest, opts ...client.CallOption) (*SecurityResponse, error) {
	req := c.c.NewRequest(c.name, "SecurityService.BindEmail", in)
	out := new(SecurityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityService) BindWx(ctx context.Context, in *SecurityRequest, opts ...client.CallOption) (*SecurityResponse, error) {
	req := c.c.NewRequest(c.name, "SecurityService.BindWx", in)
	out := new(SecurityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityService) Destroy(ctx context.Context, in *SecurityRequest, opts ...client.CallOption) (*SecurityResponse, error) {
	req := c.c.NewRequest(c.name, "SecurityService.Destroy", in)
	out := new(SecurityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SecurityService service

type SecurityServiceHandler interface {
	//判断有无密码保护
	HasPwd(context.Context, *SecurityRequest, *SecurityResponse) error
	//创建密码(未设置密码前可用)
	CreatePwd(context.Context, *SecurityRequest, *SecurityResponse) error
	//修改密码
	ModifyPwd(context.Context, *SecurityRequest, *SecurityResponse) error
	//绑定手机号
	BindMobile(context.Context, *SecurityRequest, *SecurityResponse) error
	//绑定邮箱
	BindEmail(context.Context, *SecurityRequest, *SecurityResponse) error
	//绑定微信
	BindWx(context.Context, *SecurityRequest, *SecurityResponse) error
	//注销账户
	Destroy(context.Context, *SecurityRequest, *SecurityResponse) error
}

func RegisterSecurityServiceHandler(s server.Server, hdlr SecurityServiceHandler, opts ...server.HandlerOption) error {
	type securityService interface {
		HasPwd(ctx context.Context, in *SecurityRequest, out *SecurityResponse) error
		CreatePwd(ctx context.Context, in *SecurityRequest, out *SecurityResponse) error
		ModifyPwd(ctx context.Context, in *SecurityRequest, out *SecurityResponse) error
		BindMobile(ctx context.Context, in *SecurityRequest, out *SecurityResponse) error
		BindEmail(ctx context.Context, in *SecurityRequest, out *SecurityResponse) error
		BindWx(ctx context.Context, in *SecurityRequest, out *SecurityResponse) error
		Destroy(ctx context.Context, in *SecurityRequest, out *SecurityResponse) error
	}
	type SecurityService struct {
		securityService
	}
	h := &securityServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&SecurityService{h}, opts...))
}

type securityServiceHandler struct {
	SecurityServiceHandler
}

func (h *securityServiceHandler) HasPwd(ctx context.Context, in *SecurityRequest, out *SecurityResponse) error {
	return h.SecurityServiceHandler.HasPwd(ctx, in, out)
}

func (h *securityServiceHandler) CreatePwd(ctx context.Context, in *SecurityRequest, out *SecurityResponse) error {
	return h.SecurityServiceHandler.CreatePwd(ctx, in, out)
}

func (h *securityServiceHandler) ModifyPwd(ctx context.Context, in *SecurityRequest, out *SecurityResponse) error {
	return h.SecurityServiceHandler.ModifyPwd(ctx, in, out)
}

func (h *securityServiceHandler) BindMobile(ctx context.Context, in *SecurityRequest, out *SecurityResponse) error {
	return h.SecurityServiceHandler.BindMobile(ctx, in, out)
}

func (h *securityServiceHandler) BindEmail(ctx context.Context, in *SecurityRequest, out *SecurityResponse) error {
	return h.SecurityServiceHandler.BindEmail(ctx, in, out)
}

func (h *securityServiceHandler) BindWx(ctx context.Context, in *SecurityRequest, out *SecurityResponse) error {
	return h.SecurityServiceHandler.BindWx(ctx, in, out)
}

func (h *securityServiceHandler) Destroy(ctx context.Context, in *SecurityRequest, out *SecurityResponse) error {
	return h.SecurityServiceHandler.Destroy(ctx, in, out)
}
