// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: advertService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AdvertService service

func NewAdvertServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AdvertService service

type AdvertService interface {
	List(ctx context.Context, in *AdvertWhere, opts ...client.CallOption) (*AdvertResponse, error)
}

type advertService struct {
	c    client.Client
	name string
}

func NewAdvertService(name string, c client.Client) AdvertService {
	return &advertService{
		c:    c,
		name: name,
	}
}

func (c *advertService) List(ctx context.Context, in *AdvertWhere, opts ...client.CallOption) (*AdvertResponse, error) {
	req := c.c.NewRequest(c.name, "AdvertService.List", in)
	out := new(AdvertResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AdvertService service

type AdvertServiceHandler interface {
	List(context.Context, *AdvertWhere, *AdvertResponse) error
}

func RegisterAdvertServiceHandler(s server.Server, hdlr AdvertServiceHandler, opts ...server.HandlerOption) error {
	type advertService interface {
		List(ctx context.Context, in *AdvertWhere, out *AdvertResponse) error
	}
	type AdvertService struct {
		advertService
	}
	h := &advertServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AdvertService{h}, opts...))
}

type advertServiceHandler struct {
	AdvertServiceHandler
}

func (h *advertServiceHandler) List(ctx context.Context, in *AdvertWhere, out *AdvertResponse) error {
	return h.AdvertServiceHandler.List(ctx, in, out)
}
